{
 "title": "PowerMax Capacity Metrics for KSM",
 "description": "PowerMax Capacity",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(powermax_volume_total_capacity_gigabytes,Namespace)"
    }
   },
   {
    "name": "StorageClass",
    "label": "Storage Class",
    "query": {
     "query": "label_values(powermax_storage_class_total_capacity_gigabytes,StorageClass)"
    }
   },
   {
    "name": "PVCName",
    "label": "PVC Name",
    "query": {
     "query": "label_values(powermax_volume_total_capacity_gigabytes,PersistentVolumeClaimName)"
    }
   },
   {
    "name": "PVName",
    "label": "PV Name",
    "query": {
     "query": "label_values(powermax_volume_total_capacity_gigabytes,PersistentVolumeName)"
    }
   },
   {
    "name": "Volume",
    "label": "Volume",
    "query": {
     "query": "label_values(powermax_volume_total_capacity_gigabytes,VolumeID)"
    }
   },
   {
    "name": "StorageGroup",
    "label": "Storage Group",
    "query": {
     "query": "label_values(powermax_storage_group_total_capacity_gigabytes,StorageGroupID)"
    }
   },
   {
    "name": "Srp",
    "label": "Srp",
    "query": {
     "query": "label_values(powermax_srp_total_capacity_gigabytes,SrpID)"
    }
   },
   {
    "name": "Array",
    "label": "Array",
    "query": {
     "query": "label_values(powermax_array_total_capacity_gigabytes,ArrayID)"
    }
   },
   { "name": "warning_threshold", "label": "PV % Used Warning Threshold", "query": "80" }
  ]
 },
 "panels": [
  { "title": "PVC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PVC Phase",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase) ( label_replace(kube_persistentvolumeclaim_status_phase{persistentvolumeclaim=~\"$PVCName\"},\"PVCName\", \"$1\", \"persistentvolumeclaim\", \"(.*)\") )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(kube_persistentvolumeclaim_resource_requests_storage_bytes{persistentvolumeclaim=~\"$PVCName\"},\"PVCName\", \"$1\", \"persistentvolumeclaim\", \"(.*)\")",
     "legendFormat": "{{persistentvolumeclaim}} / {{ namespace}}"
    }
   ]
  },
  {
   "title": "$StorageGroup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "StorageGroup",
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Group Capacity",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (StorageGroupID) (powermax_storage_group_used_capacity_gigabytes{ArrayID=~\"$Array\", StorageGroupID=~\"$StorageGroup\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg by (StorageGroupID) (powermax_storage_group_total_capacity_gigabytes{ArrayID=~\"$Array\", StorageGroupID=~\"$StorageGroup\"})",
       "legendFormat": "Provisioned"
      }
     ]
    },
    {
     "title": "Storage Group Summary",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "powermax_storage_group_total_capacity_gigabytes{ArrayID=~\"$Array\", StorageGroupID=~\"$StorageGroup\"}",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "powermax_storage_group_used_capacity_gigabytes{ArrayID=~\"$Array\", StorageGroupID=~\"$StorageGroup\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "$Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "Volume",
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Capacity",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (VolumeID) (powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", VolumeID=~\"$Volume\", Namespace=~\"$Namespace\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg by (VolumeID) (powermax_volume_total_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", VolumeID=~\"$Volume\", Namespace=~\"$Namespace\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Summary",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "powermax_volume_total_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", VolumeID=~\"$Volume\", Namespace=~\"$Namespace\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", VolumeID=~\"$Volume\", Namespace=~\"$Namespace\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "PVs Full in 2 days - Based on Daily Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "  count (predict_linear(powermax_volume_total_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"}[1d], 2 * 24 * 60 * 60) - predict_linear(powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"}[1d], 2 * 24 * 60 * 60) <= 0)\nor\nvector(0)"
      }
     ]
    },
    {
     "title": "PVs Full in 5 days - Based on Daily Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "  count (predict_linear(powermax_volume_total_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"}[1d], 5 * 24 * 60 * 60) - predict_linear(powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"}[1d], 5 * 24 * 60 * 60) <= 0)\nor\nvector(0)"
      }
     ]
    },
    {
     "title": "PVs Full in 1 Week - Based on Daily Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "  count (predict_linear(powermax_volume_total_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"}[1d], 7 * 24 * 60 * 60) - predict_linear(powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"}[1d], 7 * 24 * 60 * 60) <= 0)\nor\nvector(0)"
      }
     ]
    },
    {
     "title": "PVs Above Warning Threshold",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count (powermax_volume_used_capacity_percentage{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"} >= ${warning_threshold}) or vector (0)"
      }
     ]
    },
    {
     "title": "PVs in Pending Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\", PersistentVolumeStatus=\"Pending\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "PVs in Failed Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\", PersistentVolumeStatus=\"Failed\"}) or vector(0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Class Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Class Capacities",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "expr": "powermax_storage_class_used_capacity_gigabytes{StorageClass=~\"$StorageClass\"}"
      },
      {
       "expr": "powermax_storage_class_total_capacity_gigabytes{StorageClass=~\"$StorageClass\"}"
      }
     ]
    },
    {
     "title": "Storage Class Usage",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (StorageClass) (powermax_storage_class_used_capacity_percentage{StorageClass=~\"$StorageClass\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistent Volume Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Capacities",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"}"
      },
      {
       "expr": "powermax_volume_total_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\",Namespace=~\"$Namespace\"}"
      }
     ]
    },
    {
     "title": "Volume Usage",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (PersistentVolumeName) (powermax_volume_used_capacity_percentage{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$Srp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "Srp",
   "collapsed": true,
   "panels": [
    {
     "title": "Srp Capacity",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (SrpID) (powermax_srp_used_capacity_gigabytes{ArrayID=~\"$Array\", SrpID=~\"$Srp\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg by (SrpID) (powermax_srp_total_capacity_gigabytes{ArrayID=~\"$Array\", SrpID=~\"$Srp\"})",
       "legendFormat": "Provisioned"
      }
     ]
    },
    {
     "title": "Srp Summary",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "powermax_srp_total_capacity_gigabytes{ArrayID=~\"$Array\", SrpID=~\"$Srp\"}",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "powermax_srp_used_capacity_gigabytes{ArrayID=~\"$Array\", SrpID=~\"$Srp\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Array Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Array Capacities",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "powermax_array_used_capacity_gigabytes{ArrayID=~\"$Array\"}"
      },
      {
       "expr": "powermax_array_total_capacity_gigabytes{ArrayID=~\"$Array\"}"
      }
     ]
    },
    {
     "title": "Array Usage",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (ArrayID) (powermax_array_used_capacity_percentage{ArrayID=~\"$Array\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Srp Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Srp Capacities",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
     "targets": [
      {
       "expr": "powermax_srp_used_capacity_gigabytes{ArrayID=~\"$Array\", SrpID=~\"$Srp\"}"
      },
      {
       "expr": "powermax_srp_total_capacity_gigabytes{ArrayID=~\"$Array\", SrpID=~\"$Srp\"}"
      }
     ]
    },
    {
     "title": "Srp Usage",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (SrpID) (powermax_srp_used_capacity_percentage{ArrayID=~\"$Array\", SrpID=~\"$Srp\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Group Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Group Capacities",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "powermax_storage_group_used_capacity_gigabytes{ArrayID=~\"$Array\", StorageGroupID=~\"$StorageGroup\"}"
      },
      {
       "expr": "powermax_storage_group_total_capacity_gigabytes{ArrayID=~\"$Array\", StorageGroupID=~\"$StorageGroup\"}"
      }
     ]
    },
    {
     "title": "Storage Group Usage",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (StorageGroupID) (powermax_storage_group_used_capacity_percentage{ArrayID=~\"$Array\", StorageGroupID=~\"$StorageGroup\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$StorageClass",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "StorageClass",
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Class Capacity",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (StorageClass) (powermax_storage_class_used_capacity_gigabytes{StorageClass=~\"$StorageClass\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg by (StorageClass) (powermax_storage_class_total_capacity_gigabytes{StorageClass=~\"$StorageClass\"})",
       "legendFormat": "Provisioned"
      }
     ]
    },
    {
     "title": "Storage Class Summary",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "powermax_storage_class_total_capacity_gigabytes{StorageClass=~\"$StorageClass\"}",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "powermax_storage_class_used_capacity_gigabytes{StorageClass=~\"$StorageClass\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  { "title": "$Array", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "Array" },
  {
   "title": "Array Capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (ArrayID) (powermax_array_used_capacity_gigabytes{ArrayID=~\"$Array\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (ArrayID) (powermax_array_total_capacity_gigabytes{ArrayID=~\"$Array\"})",
     "legendFormat": "Provisioned"
    }
   ]
  },
  {
   "title": "Array Summary",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "powermax_array_total_capacity_gigabytes{ArrayID=~\"$Array\"}",
     "legendFormat": "Provisioned"
    },
    {
     "expr": "powermax_array_used_capacity_gigabytes{ArrayID=~\"$Array\"}",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}