{
 "title": "PowerScale Volume Capacity for KSM",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "PVCName",
    "label": "PVC Name",
    "query": {
     "query": "label_values(powerscale_volume_quota_subscribed_gigabytes,PersistentVolumeClaim)"
    }
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(powerscale_volume_quota_subscribed_gigabytes,Namespace)"
    }
   },
   {
    "name": "ClusterName",
    "label": "PowerScale Cluster Name",
    "query": {
     "query": "label_values(powerscale_volume_quota_subscribed_gigabytes,ClusterName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "PVC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PVC Phase",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase) ( label_replace(kube_persistentvolumeclaim_status_phase{persistentvolumeclaim=~\"$PVCName\"},\"PVCName\", \"$1\", \"persistentvolumeclaim\", \"(.*)\") )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(kube_persistentvolumeclaim_resource_requests_storage_bytes{persistentvolumeclaim=~\"$PVCName\",namespace=~\"$Namespace\"},\"PVCName\", \"$1\", \"persistentvolumeclaim\", \"(.*)\")",
     "legendFormat": "{{persistentvolumeclaim}} / {{ namespace}}"
    }
   ]
  },
  { "title": "Volume Capacity Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Volume Quota",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "powerscale_volume_hard_quota_remaining_gigabytes{ClusterName=~\"$ClusterName\", PersistentVolumeClaim=~\"$PVCName\",Namespace=~\"$Namespace\"}"
    },
    {
     "expr": "powerscale_volume_quota_subscribed_gigabytes{ClusterName=~\"$ClusterName\", PersistentVolumeClaim=~\"$PVCName\",Namespace=~\"$Namespace\"}"
    }
   ]
  }
 ]
}