{
 "title": "Volume Performance metrics for Powerstore",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "IP",
    "query": {
     "query": "label_values(powerstore_cluster,IP)"
    }
   },
   {
    "name": "Appliance",
    "query": {
     "query": "label_values(powerstore_appliance,appliance_id)"
    }
   },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_pod_info,node)"
    }
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "query_result(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$Namespace\", node=\"$Node\"}* on (persistentvolumeclaim, namespace) group_left(volumename)kube_persistentvolumeclaim_info * on (volumename) group_left()label_replace(  kube_persistentvolume_info{csi_driver=\"csi-powerstore.dellemc.com\"},  \"volumename\",  \"$1\",  \"persistentvolume\",  \"(.*)\"))"
    }
   },
   {
    "name": "PVCName",
    "label": "PVCName",
    "query": {
     "query": "query_result(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$Namespace\", pod=\"$Pod\"}* on (persistentvolumeclaim, namespace) group_left(volumename)kube_persistentvolumeclaim_info * on (volumename) group_left()label_replace(  kube_persistentvolume_info{csi_driver=\"csi-powerstore.dellemc.com\"},  \"volumename\",  \"$1\",  \"persistentvolume\",  \"(.*)\"))"
    }
   },
   {
    "name": "PVName",
    "label": "PVName",
    "query": {
     "query": "query_result(kube_persistentvolume_info{csi_driver=\"csi-powerstore.dellemc.com\"} *on(persistentvolume)group_left(persistentvolumeclaim) label_replace(kube_persistentvolumeclaim_info{persistentvolumeclaim=\"$PVCName\"}, \"persistentvolume\", \"$1\", \"volumename\", \"(.*)\"))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Information",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "last_over_time(powerstore_cluster{IP=\"$IP\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_appliance{IP=\"$IP\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_perf_io_workload_cpu_utilization{IP=\"$IP\"}[1h])*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_cap_last_efficiency_ratio{IP=\"$IP\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_cap_last_logical_provisioned{IP=\"$IP\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_cap_last_physical_used{IP=\"$IP\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_cap_last_physical_total{IP=\"$IP\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_cap_last_logical_used{IP=\"$IP\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(powerstore_perf_avg_io_workload_cpu_utilization{IP=\"$IP\"}[1h])*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Powerstore Appliance latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "powerstore_perf_avg_latency{IP=\"$IP\"} * 0.001",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Powerstore Appliance Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "powerstore_perf_avg_total_bandwidth{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Powerstore Appliance IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "powerstore_perf_avg_total_iops{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Powerstore Appliance IO Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "powerstore_perf_avg_io_size{IP=\"$IP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "[$Appliance] Volume Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "powerstore_metricVolume_avg_latency{IP=\"$IP\", appliance_id=\"$Appliance\", volume_id=\"$PVName\"}   * on (volume_id)\r\n    group_left(persistentvolume)\r\n  label_replace(\r\n    max by (persistentvolume, csi_volume_handle) (\r\n      kube_persistentvolume_info\r\n    ),\r\n    \"volume_id\", \"$1\", \"persistentvolume\", \"(.*)\"\r\n  ) * 0.001",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance]  Volume Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "powerstore_metricVolume_avg_write_bandwidth{IP=\"$IP\",appliance_id=\"$Appliance\", volume_id=\"$PVName\"}   * on (volume_id)\r\n    group_left(persistentvolume)\r\n  label_replace(\r\n    max by (persistentvolume, csi_volume_handle) (\r\n      kube_persistentvolume_info\r\n    ),\r\n    \"volume_id\", \"$1\", \"persistentvolume\", \"(.*)\"\r\n  ) + powerstore_metricVolume_avg_read_bandwidth{IP=\"$IP\",appliance_id=\"$Appliance\", volume_id=\"$PVName\"}   * on (volume_id)\r\n    group_left(persistentvolume)\r\n  label_replace(\r\n    max by (persistentvolume, csi_volume_handle) (\r\n      kube_persistentvolume_info\r\n    ),\r\n    \"volume_id\", \"$1\", \"persistentvolume\", \"(.*)\"\r\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] Volume Total IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "powerstore_metricVolume_avg_read_iops{IP=\"$IP\",appliance_id=\"$Appliance\", volume_id=\"$PVName\"}   * on (volume_id)\r\n    group_left(persistentvolume)\r\n  label_replace(\r\n    max by (persistentvolume, csi_volume_handle) (\r\n      kube_persistentvolume_info\r\n    ),\r\n    \"volume_id\", \"$1\", \"persistentvolume\", \"(.*)\"\r\n  ) + powerstore_metricVolume_avg_write_iops{IP=\"$IP\",appliance_id=\"$Appliance\", volume_id=\"$PVName\"}   * on (volume_id)\r\n    group_left(persistentvolume)\r\n  label_replace(\r\n    max by (persistentvolume, csi_volume_handle) (\r\n      kube_persistentvolume_info\r\n    ),\r\n    \"volume_id\", \"$1\", \"persistentvolume\", \"(.*)\"\r\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] Volume Total IO Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "powerstore_metricVolume_avg_io_size{IP=\"$IP\",appliance_id=\"$Appliance\", volume_id=\"$PVName\"}   * on (volume_id)\r\n    group_left(persistentvolume)\r\n  label_replace(\r\n    max by (persistentvolume, csi_volume_handle) (\r\n      kube_persistentvolume_info\r\n    ),\r\n    \"volume_id\", \"$1\", \"persistentvolume\", \"(.*)\"\r\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[$Appliance] Volume Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "powerstore_volume_size{IP=\"$IP\",appliance_id=\"$Appliance\"} * on (name)\r\n    group_left(persistentvolume)\r\n  label_replace(\r\n    max by (persistentvolume, csi_volume_handle) (kube_persistentvolume_info),\r\n    \"name\", \"$1\", \"persistentvolume\", \"(.*)\"\r\n  )",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_volume_state{IP=\"$IP\",appliance_id=\"$Appliance\"} * on (name)\r\n    group_left(persistentvolume)\r\n  label_replace(\r\n    max by (persistentvolume, csi_volume_handle) (kube_persistentvolume_info),\r\n    \"name\", \"$1\", \"persistentvolume\", \"(.*)\"\r\n  )",
     "legendFormat": "__auto"
    },
    {
     "expr": "powerstore_volume_logical_used{IP=\"$IP\",appliance_id=\"$Appliance\"} * on (name)\r\n    group_left(persistentvolume)\r\n  label_replace(\r\n    max by (persistentvolume, csi_volume_handle) (kube_persistentvolume_info),\r\n    \"name\", \"$1\", \"persistentvolume\", \"(.*)\"\r\n  )",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}