{
 "title": "PowerScale Cluster IO Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ShowMean", "label": "Hide Details", "query": "Yes, No" },
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(powerscale_cluster_disk_read_operation_rate,ClusterName)"
   },
   { "name": "TopX", "label": "Ranking", "query": "2,5,10,15,20,100" },
   {
    "name": "TimeFrame",
    "label": "Average over Time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerscale_cluster_cpu_use_rate{PlotWithMean=~\"($ShowMean)\", ClusterName=~\"$ClusterName\"} and topk($TopX, avg_over_time(powerscale_cluster_cpu_use_rate{PlotWithMean=~\"($ShowMean)\", ClusterName=~\"$ClusterName\"}[$TimeFrame]))",
     "legendFormat": "{{ClusterName}}"
    },
    {
     "expr": "sum(powerscale_cluster_cpu_use_rate{PlotWithMean=~\"($ShowMean)|No\", ClusterName=~\"$ClusterName\"}) / count(powerscale_cluster_cpu_use_rate{PlotWithMean=~\"($ShowMean)|No\",ClusterName=~\"$ClusterName\"})",
     "legendFormat": "Average CPU Usage"
    }
   ]
  },
  {
   "title": "Disk Read Operation Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerscale_cluster_disk_read_operation_rate{PlotWithMean=~\"($ShowMean)\", ClusterName=~\"$ClusterName\"} and topk($TopX, avg_over_time(powerscale_cluster_disk_read_operation_rate{PlotWithMean=~\"($ShowMean)\", ClusterName=~\"$ClusterName\"}[$TimeFrame]))",
     "legendFormat": "{{ClusterName}}"
    },
    {
     "expr": "sum(powerscale_cluster_disk_read_operation_rate{PlotWithMean=~\"($ShowMean)|No\", ClusterName=~\"$ClusterName\"}) / count(powerscale_cluster_disk_read_operation_rate{PlotWithMean=~\"($ShowMean)|No\",ClusterName=~\"$ClusterName\"})",
     "legendFormat": "Average Read Operation Rate"
    }
   ]
  },
  {
   "title": "Disk Write Operation Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerscale_cluster_disk_write_operation_rate{PlotWithMean=~\"($ShowMean)\", ClusterName=~\"$ClusterName\"} and topk($TopX, avg_over_time(powerscale_cluster_disk_write_operation_rate{PlotWithMean=~\"($ShowMean)\", ClusterName=~\"$ClusterName\"}[$TimeFrame]))",
     "legendFormat": "{{ClusterName}}"
    },
    {
     "expr": "sum(powerscale_cluster_disk_write_operation_rate{PlotWithMean=~\"($ShowMean)|No\", ClusterName=~\"$ClusterName\"}) / count(powerscale_cluster_disk_write_operation_rate{PlotWithMean=~\"($ShowMean)|No\",ClusterName=~\"$ClusterName\"})",
     "legendFormat": "Average Write Operation Rate"
    }
   ]
  },
  {
   "title": "Disk Read Throughput (MB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerscale_cluster_disk_throughput_read_rate_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ClusterName=~\"$ClusterName\"} and topk($TopX, avg_over_time(powerscale_cluster_disk_throughput_read_rate_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ClusterName=~\"$ClusterName\"}[$TimeFrame]))",
     "legendFormat": "{{ClusterName}}"
    },
    {
     "expr": "sum(powerscale_cluster_disk_throughput_read_rate_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", ClusterName=~\"$ClusterName\"}) / count(powerscale_cluster_disk_throughput_read_rate_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\",ClusterName=~\"$ClusterName\"})",
     "legendFormat": "Average Read Throughput Rate"
    }
   ]
  },
  {
   "title": "Disk Write Throughput (MB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerscale_cluster_disk_throughput_write_rate_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ClusterName=~\"$ClusterName\"} and topk($TopX, avg_over_time(powerscale_cluster_disk_throughput_write_rate_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ClusterName=~\"$ClusterName\"}[$TimeFrame]))",
     "legendFormat": "{{ClusterName}}"
    },
    {
     "expr": "sum(powerscale_cluster_disk_throughput_write_rate_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", ClusterName=~\"$ClusterName\"}) / count(powerscale_cluster_disk_throughput_write_rate_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\",ClusterName=~\"$ClusterName\"})",
     "legendFormat": "Average Write Throughput Rate"
    }
   ]
  }
 ]
}