{
 "title": "PowerScale Volume Capacity",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "PVName",
    "label": "PV Name",
    "query": {
     "query": "label_values(powerscale_volume_quota_subscribed_gigabytes,PersistentVolumeName)"
    }
   },
   {
    "name": "PVCName",
    "label": "PVC Name",
    "query": {
     "query": "label_values(powerscale_volume_quota_subscribed_gigabytes,PersistentVolumeClaim)"
    }
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(powerscale_volume_quota_subscribed_gigabytes,Namespace)"
    }
   },
   {
    "name": "VolumeID",
    "label": "Volume ID",
    "query": {
     "query": "label_values(powerscale_volume_quota_subscribed_gigabytes,VolumeID)"
    }
   },
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(powerscale_volume_quota_subscribed_gigabytes,ClusterName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Volume Capacity Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume Quota",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "powerscale_volume_hard_quota_remaining_gigabytes{ClusterName=~\"$ClusterName\", PersistentVolumeClaim=~\"$PVCName\",Namespace=~\"$Namespace\"}"
    },
    {
     "expr": "powerscale_volume_quota_subscribed_gigabytes{ClusterName=~\"$ClusterName\", PersistentVolumeClaim=~\"$PVCName\",Namespace=~\"$Namespace\"}"
    }
   ]
  },
  {
   "title": "Volume Quota Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (ClusterName) (powerscale_volume_quota_subscribed_gigabytes{ClusterName=~\"$ClusterName\", PersistentVolumeClaim=~\"$PVCName\",Namespace=~\"$Namespace\"}*100 / (powerscale_volume_hard_quota_remaining_gigabytes{ClusterName=~\"$ClusterName\", PersistentVolumeClaim=~\"$PVCName\",Namespace=~\"$Namespace\"} + powerscale_volume_quota_subscribed_gigabytes{ClusterName=~\"$ClusterName\", PersistentVolumeClaim=~\"$PVCName\",Namespace=~\"$Namespace\"}))"
    }
   ]
  },
  {
   "title": "$VolumeID",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "VolumeID",
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Quota Capacity",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(VolumeID) (powerscale_volume_quota_subscribed_gigabytes{ClusterName=~\"$ClusterName\",PersistentVolumeName=~\"$PVName\",VolumeID=~\"$VolumeID\", PersistentVolumeClaim=~\"$PVCName\",Namespace=~\"$Namespace\"})",
       "legendFormat": "Subscribed"
      },
      {
       "expr": "avg by(VolumeID) (powerscale_volume_hard_quota_remaining_gigabytes{ClusterName=~\"$ClusterName\",PersistentVolumeName=~\"$PVName\",VolumeID=~\"$VolumeID\", PersistentVolumeClaim=~\"$PVCName\",Namespace=~\"$Namespace\"})",
       "legendFormat": "Remaining"
      }
     ]
    },
    {
     "title": "Volume Quota Summary",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "format": "decgbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "powerscale_volume_quota_subscribed_gigabytes{ClusterName=~\"$ClusterName\",PersistentVolumeName=~\"$PVName\",VolumeID=~\"$VolumeID\", PersistentVolumeClaim=~\"$PVCName\",Namespace=~\"$Namespace\"}",
       "legendFormat": "Quota Subscribed"
      },
      {
       "expr": "powerscale_volume_hard_quota_remaining_gigabytes{ClusterName=~\"$ClusterName\",PersistentVolumeName=~\"$PVName\",VolumeID=~\"$VolumeID\", PersistentVolumeClaim=~\"$PVCName\",Namespace=~\"$Namespace\"}",
       "legendFormat": "Quota Remaining"
      }
     ]
    }
   ]
  }
 ]
}