{
 "title": "PowerMax Performance Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ShowMean", "label": "Hide Details", "query": "Yes, No" },
   {
    "name": "ArrayID",
    "label": "Symmetrix ID",
    "query": {
     "query": "label_values(powermax_storage_group_average_io_size_megabytes_per_second,ArrayID)"
    }
   },
   { "name": "TopX", "label": "Ranking", "query": "2,5,10,15,20,100" },
   {
    "name": "TimeFrame",
    "label": "Average over Time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "VolumeID",
    "label": "Volume ID",
    "query": {
     "query": "label_values(powermax_volume_read_bw_megabytes_per_second,VolumeID)"
    }
   },
   {
    "name": "StorageClass",
    "label": "Storage Class",
    "query": {
     "query": "label_values(powermax_volume_read_bw_megabytes_per_second,StorageClass)"
    }
   },
   {
    "name": "PVName",
    "label": "PV Name",
    "query": {
     "query": "label_values(powermax_volume_read_bw_megabytes_per_second,PersistentVolumeName)"
    }
   },
   {
    "name": "PersistentVolumeClaimName",
    "label": "PVC Name",
    "query": {
     "query": "label_values(powermax_volume_read_bw_megabytes_per_second,PersistentVolumeClaimName)"
    }
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(powermax_volume_read_bw_megabytes_per_second,Namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Storage Group Average IO Size (MB/S)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powermax_storage_group_average_io_size_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"} and topk($TopX, avg_over_time(powermax_storage_group_average_io_size_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"}[$TimeFrame]))",
     "legendFormat": "{{ArrayID}}"
    },
    {
     "expr": "sum(powermax_storage_group_average_io_size_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", ArrayID=~\"$ArrayID\"}) / count(powermax_storage_group_average_io_size_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\",ArrayID=~\"$ArrayID\"})",
     "legendFormat": "Average IO Size"
    }
   ]
  },
  {
   "title": "Storage Group Read Bandwidth (MB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powermax_storage_group_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"} and topk($TopX, avg_over_time(powermax_storage_group_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"}[$TimeFrame]))",
     "legendFormat": "{{ArrayID}}"
    },
    {
     "expr": "sum(powermax_storage_group_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", ArrayID=~\"$ArrayID\"}) / count(powermax_storage_group_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\",ArrayID=~\"$ArrayID\"})",
     "legendFormat": "Average Read Bandwidth"
    }
   ]
  },
  {
   "title": "Storage Group Write Bandwidth (MB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powermax_storage_group_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"} and topk($TopX, avg_over_time(powermax_storage_group_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"}[$TimeFrame]))",
     "legendFormat": "{{ArrayID}}"
    },
    {
     "expr": "sum(powermax_storage_group_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", ArrayID=~\"$ArrayID\"}) / count(powermax_storage_group_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\",ArrayID=~\"$ArrayID\"})",
     "legendFormat": "Average Write Bandwidth"
    }
   ]
  },
  {
   "title": "Storage Group Read Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powermax_storage_group_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"} and topk($TopX, avg_over_time(powermax_storage_group_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"}[$TimeFrame]))",
     "legendFormat": "{{ArrayID}}"
    },
    {
     "expr": "sum(powermax_storage_group_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\", ArrayID=~\"$ArrayID\"}) / count(powermax_storage_group_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\",ArrayID=~\"$ArrayID\"})",
     "legendFormat": "Average Read Latency"
    }
   ]
  },
  {
   "title": "Storage Group Write Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powermax_storage_group_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"} and topk($TopX, avg_over_time(powermax_storage_group_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"}[$TimeFrame]))",
     "legendFormat": "{{ArrayID}}"
    },
    {
     "expr": "sum(powermax_storage_group_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\", ArrayID=~\"$ArrayID\"}) / count(powermax_storage_group_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\",ArrayID=~\"$ArrayID\"})",
     "legendFormat": "Average Write Latency"
    }
   ]
  },
  {
   "title": "Storage Group Read IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powermax_storage_group_read_io_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"} and topk($TopX, avg_over_time(powermax_storage_group_read_io_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"}[$TimeFrame]))",
     "legendFormat": "{{ArrayID}}"
    },
    {
     "expr": "sum(powermax_storage_group_read_io_per_second{PlotWithMean=~\"($ShowMean)|No\", ArrayID=~\"$ArrayID\"}) / count(powermax_storage_group_read_io_per_second{PlotWithMean=~\"($ShowMean)|No\",ArrayID=~\"$ArrayID\"})",
     "legendFormat": "Average Read IOPS"
    }
   ]
  },
  {
   "title": "Storage Group Write IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powermax_storage_group_write_io_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"} and topk($TopX, avg_over_time(powermax_storage_group_write_io_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"}[$TimeFrame]))",
     "legendFormat": "{{ArrayID}}"
    },
    {
     "expr": "sum(powermax_storage_group_write_io_per_second{PlotWithMean=~\"($ShowMean)|No\", ArrayID=~\"$ArrayID\"}) / count(powermax_storage_group_write_io_per_second{PlotWithMean=~\"($ShowMean)|No\",ArrayID=~\"$ArrayID\"})",
     "legendFormat": "Average Write IOPS"
    }
   ]
  },
  {
   "title": "Volume Read Bandwidth (MB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powermax_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powermax_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{VolumeID}}"
    },
    {
     "expr": "sum(powermax_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}) / count(powermax_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"})",
     "legendFormat": "Average Read Bandwidth"
    }
   ]
  },
  {
   "title": "Volume Write Bandwidth (MB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powermax_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powermax_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{VolumeID}}"
    },
    {
     "expr": "sum(powermax_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}) / count(powermax_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"})",
     "legendFormat": "Average Write Bandwidth"
    }
   ]
  },
  {
   "title": "Volume Read Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powermax_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powermax_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{VolumeID}}"
    },
    {
     "expr": "sum(powermax_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}) / count(powermax_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"})",
     "legendFormat": "Average Read Latency"
    }
   ]
  },
  {
   "title": "Volume Write Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powermax_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powermax_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{VolumeID}}"
    },
    {
     "expr": "sum(powermax_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}) / count(powermax_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"})",
     "legendFormat": "Average Write Latency"
    }
   ]
  },
  {
   "title": "Volume Read IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powermax_volume_read_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powermax_volume_read_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{VolumeID}}"
    },
    {
     "expr": "sum(powermax_volume_read_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}) / count(powermax_volume_read_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"})",
     "legendFormat": "Average Read IOPS"
    }
   ]
  },
  {
   "title": "Volume Write IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powermax_volume_write_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powermax_volume_write_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{VolumeID}}"
    },
    {
     "expr": "sum(powermax_volume_write_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}) / count(powermax_volume_write_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"})",
     "legendFormat": "Average Write IOPS"
    }
   ]
  }
 ]
}