{
 "title": "PowerMax Capacity",
 "description": "PowerMax Capacity",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(powermax_volume_total_capacity_gigabytes,Namespace)"
    }
   },
   {
    "name": "StorageClass",
    "label": "Storage Class",
    "query": {
     "query": "label_values(powermax_storage_class_total_capacity_gigabytes,StorageClass)"
    }
   },
   {
    "name": "PVCName",
    "label": "PVC Name",
    "query": {
     "query": "label_values(powermax_volume_total_capacity_gigabytes,PersistentVolumeClaimName)"
    }
   },
   {
    "name": "PVName",
    "label": "PV Name",
    "query": {
     "query": "label_values(powermax_volume_total_capacity_gigabytes,PersistentVolumeName)"
    }
   },
   {
    "name": "Volume",
    "label": "Volume",
    "query": {
     "query": "label_values(powermax_volume_total_capacity_gigabytes,VolumeID)"
    }
   },
   {
    "name": "StorageGroup",
    "label": "Storage Group",
    "query": {
     "query": "label_values(powermax_storage_group_total_capacity_gigabytes,StorageGroupID)"
    }
   },
   {
    "name": "Srp",
    "label": "Srp",
    "query": {
     "query": "label_values(powermax_srp_total_capacity_gigabytes,SrpID)"
    }
   },
   {
    "name": "Array",
    "label": "Array",
    "query": {
     "query": "label_values(powermax_array_total_capacity_gigabytes,ArrayID)"
    }
   },
   { "name": "warning_threshold", "label": "PV % Used Warning Threshold", "query": "80" }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PVs Full in 2 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "  count (predict_linear(powermax_volume_total_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"}[1d], 2 * 24 * 60 * 60) - predict_linear(powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"}[1d], 2 * 24 * 60 * 60) <= 0)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVs Full in 5 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "  count (predict_linear(powermax_volume_total_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"}[1d], 5 * 24 * 60 * 60) - predict_linear(powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"}[1d], 5 * 24 * 60 * 60) <= 0)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVs Full in 1 Week - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "  count (predict_linear(powermax_volume_total_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"}[1d], 7 * 24 * 60 * 60) - predict_linear(powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"}[1d], 7 * 24 * 60 * 60) <= 0)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVs Above Warning Threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (powermax_volume_used_capacity_percentage{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"} >= ${warning_threshold}) or vector (0)"
    }
   ]
  },
  {
   "title": "PVs in Pending Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\", PersistentVolumeStatus=\"Pending\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "PVs in Failed Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\", PersistentVolumeStatus=\"Failed\"}) or vector(0)"
    }
   ]
  },
  { "title": "Storage Class Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Storage Class Capacities",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "powermax_storage_class_used_capacity_gigabytes{StorageClass=~\"$StorageClass\"}"
    },
    {
     "expr": "powermax_storage_class_total_capacity_gigabytes{StorageClass=~\"$StorageClass\"}"
    }
   ]
  },
  {
   "title": "Storage Class Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (StorageClass) (powermax_storage_class_used_capacity_percentage{StorageClass=~\"$StorageClass\"})"
    }
   ]
  },
  { "title": "Persistent Volume Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Volume Capacities",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"}"
    },
    {
     "expr": "powermax_volume_total_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\",Namespace=~\"$Namespace\"}"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (PersistentVolumeName) (powermax_volume_used_capacity_percentage{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", Namespace=~\"$Namespace\"})"
    }
   ]
  },
  { "title": "Array Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Array Capacities",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "powermax_array_used_capacity_gigabytes{ArrayID=~\"$Array\"}"
    },
    {
     "expr": "powermax_array_total_capacity_gigabytes{ArrayID=~\"$Array\"}"
    }
   ]
  },
  {
   "title": "Array Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (ArrayID) (powermax_array_used_capacity_percentage{ArrayID=~\"$Array\"})"
    }
   ]
  },
  { "title": "Srp Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Srp Capacities",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "powermax_srp_used_capacity_gigabytes{ArrayID=~\"$Array\", SrpID=~\"$Srp\"}"
    },
    {
     "expr": "powermax_srp_total_capacity_gigabytes{ArrayID=~\"$Array\", SrpID=~\"$Srp\"}"
    }
   ]
  },
  {
   "title": "Srp Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (SrpID) (powermax_srp_used_capacity_percentage{ArrayID=~\"$Array\", SrpID=~\"$Srp\"})"
    }
   ]
  },
  { "title": "Storage Group Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Storage Group Capacities",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "powermax_storage_group_used_capacity_gigabytes{ArrayID=~\"$Array\", StorageGroupID=~\"$StorageGroup\"}"
    },
    {
     "expr": "powermax_storage_group_total_capacity_gigabytes{ArrayID=~\"$Array\", StorageGroupID=~\"$StorageGroup\"}"
    }
   ]
  },
  {
   "title": "Storage Group Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (StorageGroupID) (powermax_storage_group_used_capacity_percentage{ArrayID=~\"$Array\", StorageGroupID=~\"$StorageGroup\"})"
    }
   ]
  },
  {
   "title": "$StorageClass",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "repeat": "StorageClass",
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Class Capacity",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (StorageClass) (powermax_storage_class_used_capacity_gigabytes{StorageClass=~\"$StorageClass\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg by (StorageClass) (powermax_storage_class_total_capacity_gigabytes{StorageClass=~\"$StorageClass\"})",
       "legendFormat": "Provisioned"
      }
     ]
    },
    {
     "title": "Storage Class Summary",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "format": "decgbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "powermax_storage_class_total_capacity_gigabytes{StorageClass=~\"$StorageClass\"}",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "powermax_storage_class_used_capacity_gigabytes{StorageClass=~\"$StorageClass\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "$Array",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "repeat": "Array",
   "collapsed": true,
   "panels": [
    {
     "title": "Array Capacity",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (ArrayID) (powermax_array_used_capacity_gigabytes{ArrayID=~\"$Array\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg by (ArrayID) (powermax_array_total_capacity_gigabytes{ArrayID=~\"$Array\"})",
       "legendFormat": "Provisioned"
      }
     ]
    },
    {
     "title": "Array Summary",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "format": "decgbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "powermax_array_total_capacity_gigabytes{ArrayID=~\"$Array\"}",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "powermax_array_used_capacity_gigabytes{ArrayID=~\"$Array\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "$Srp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "repeat": "Srp",
   "collapsed": true,
   "panels": [
    {
     "title": "Srp Capacity",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (SrpID) (powermax_srp_used_capacity_gigabytes{ArrayID=~\"$Array\", SrpID=~\"$Srp\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg by (SrpID) (powermax_srp_total_capacity_gigabytes{ArrayID=~\"$Array\", SrpID=~\"$Srp\"})",
       "legendFormat": "Provisioned"
      }
     ]
    },
    {
     "title": "Srp Summary",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "format": "decgbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "powermax_srp_total_capacity_gigabytes{ArrayID=~\"$Array\", SrpID=~\"$Srp\"}",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "powermax_srp_used_capacity_gigabytes{ArrayID=~\"$Array\", SrpID=~\"$Srp\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "$StorageGroup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "repeat": "StorageGroup",
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Group Capacity",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (StorageGroupID) (powermax_storage_group_used_capacity_gigabytes{ArrayID=~\"$Array\", StorageGroupID=~\"$StorageGroup\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg by (StorageGroupID) (powermax_storage_group_total_capacity_gigabytes{ArrayID=~\"$Array\", StorageGroupID=~\"$StorageGroup\"})",
       "legendFormat": "Provisioned"
      }
     ]
    },
    {
     "title": "Storage Group Summary",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "format": "decgbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "powermax_storage_group_total_capacity_gigabytes{ArrayID=~\"$Array\", StorageGroupID=~\"$StorageGroup\"}",
       "legendFormat": "Provisioned"
      },
      {
       "expr": "powermax_storage_group_used_capacity_gigabytes{ArrayID=~\"$Array\", StorageGroupID=~\"$StorageGroup\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  },
  {
   "title": "$Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "repeat": "Volume",
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Capacity",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (VolumeID) (powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", VolumeID=~\"$Volume\", Namespace=~\"$Namespace\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg by (VolumeID) (powermax_volume_total_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", VolumeID=~\"$Volume\", Namespace=~\"$Namespace\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Volume Summary",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "format": "decgbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "powermax_volume_total_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", VolumeID=~\"$Volume\", Namespace=~\"$Namespace\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "powermax_volume_used_capacity_gigabytes{ArrayID=~\"$Array\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", VolumeID=~\"$Volume\", Namespace=~\"$Namespace\"}",
       "legendFormat": "Used"
      }
     ]
    }
   ]
  }
 ]
}