{
 "title": "PowerFlex Storage System I/O Metrics by Node",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ShowMean", "label": "Hide Details", "query": "Yes, No" },
   { "name": "TopX", "label": "Ranking", "query": "2,5,10,15,20,100,1000" },
   {
    "name": "TimeFrame",
    "label": "Average over Time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "Node_Name",
    "label": "Node Name",
    "query": "label_values(powerflex_export_node_read_bw_megabytes_per_second, Name)"
   },
   {
    "name": "Node_IP",
    "label": "Node IP",
    "query": "label_values(powerflex_export_node_read_bw_megabytes_per_second, IP)"
   }
  ]
 },
 "panels": [
  {
   "title": "PowerFlex Read IOPS by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerflex_export_node_read_iops_per_second{PlotWithMean=~\"($ShowMean)\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"} and topk($TopX, avg_over_time(powerflex_export_node_read_iops_per_second{PlotWithMean=~ \"($ShowMean)\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"}[$TimeFrame]))",
     "legendFormat": "{{Name}}"
    },
    {
     "expr": "sum(powerflex_export_node_read_iops_per_second{PlotWithMean=~\"($ShowMean)|No\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"}) / count(powerflex_export_node_read_iops_per_second{PlotWithMean=~\"($ShowMean)|No\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"})",
     "legendFormat": "Average ReadIOPS"
    }
   ]
  },
  {
   "title": "PowerFlex Write IOPS by Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerflex_export_node_write_iops_per_second{PlotWithMean=~\"($ShowMean)\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"} and topk($TopX, avg_over_time(powerflex_export_node_write_iops_per_second{PlotWithMean=~\"($ShowMean)\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"}[$TimeFrame]))",
     "legendFormat": "{{Name}}"
    },
    {
     "expr": "sum(powerflex_export_node_write_iops_per_second{PlotWithMean=~\"($ShowMean)|No\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"}) / count(powerflex_export_node_write_iops_per_second{PlotWithMean=~\"($ShowMean)|No\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"})",
     "legendFormat": "Average WriteIOP"
    }
   ]
  },
  {
   "title": "PowerFlex Read Latency by Node(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerflex_export_node_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"} and topk($TopX, avg_over_time(powerflex_export_node_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"}[$TimeFrame]))",
     "legendFormat": "{{Name}}"
    },
    {
     "expr": "sum(powerflex_export_node_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"}) / count(powerflex_export_node_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"})",
     "legendFormat": "Average ReadLatency"
    }
   ]
  },
  {
   "title": "PowerFlex Write Latency by Node (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerflex_export_node_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"} and topk($TopX, avg_over_time(powerflex_export_node_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"}[$TimeFrame]))",
     "legendFormat": "{{Name}}"
    },
    {
     "expr": "sum(powerflex_export_node_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"}) / count(powerflex_export_node_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"})",
     "legendFormat": "Average WriteLatency"
    }
   ]
  },
  {
   "title": "PowerFlex Read Bandwidth by Node (MB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerflex_export_node_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"} and topk($TopX, avg_over_time(powerflex_export_node_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"}[$TimeFrame]))",
     "legendFormat": "{{Name}}"
    },
    {
     "expr": "sum(powerflex_export_node_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"}) / count(powerflex_export_node_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"})",
     "legendFormat": "Average Read BW"
    }
   ]
  },
  {
   "title": "PowerFlex Write Bandwidth by Node(MB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerflex_export_node_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"} and topk($TopX, avg_over_time(powerflex_export_node_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"}[$TimeFrame]))",
     "legendFormat": "{{Name}}"
    },
    {
     "expr": "sum(powerflex_export_node_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"}) / count(powerflex_export_node_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", Name=~\"$Node_Name\", IP =~\"($Node_IP)\"})",
     "legendFormat": "Average Write BW"
    }
   ]
  }
 ]
}