{
 "title": "Storage Pool and Storage Class Capacity",
 "description": "Storage Pool and Storage Class Capacity",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "StorageClass", "query": "label_values(StorageClass)" },
   { "name": "StoragePool", "query": "label_values(StoragePool)" },
   { "name": "Driver", "query": "label_values(Driver)" },
   {
    "name": "StorageSystemName",
    "query": "label_values(StorageSystemName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Capacities",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "powerflex_storage_pool_total_logical_capacity_gigabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\",StoragePool=~\"$StoragePool\",StorageSystemName=~\"$StorageSystemName\"}\r"
    },
    {
     "expr": "powerflex_storage_pool_logical_capacity_available_gigabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\",StoragePool=~\"$StoragePool\",StorageSystemName=~\"$StorageSystemName\"}\r"
    },
    {
     "expr": "powerflex_storage_pool_logical_provisioned_gigabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\",StoragePool=~\"$StoragePool\",StorageSystemName=~\"$StorageSystemName\"}"
    }
   ]
  },
  {
   "title": "Storage Pool Usage Capacity",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_source",
     "expr": "avg by (StoragePool) (powerflex_storage_pool_logical_capacity_in_use_gigabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\",StoragePool=~\"$StoragePool\",StorageSystemName=~\"$StorageSystemName\"}*100 / powerflex_storage_pool_total_logical_capacity_gigabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\",StoragePool=~\"$StoragePool\",StorageSystemName=~\"$StorageSystemName\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{StoragePool}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$StoragePool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "StoragePool" },
  {
   "title": "Total Capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Capacity",
     "expr": "avg by (StoragePool) (powerflex_storage_pool_total_logical_capacity_gigabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\",StoragePool=~\"$StoragePool\",StorageSystemName=~\"$StorageSystemName\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Total Capacity"
    },
    {
     "alias": "Free Capacity",
     "expr": "avg by (StoragePool) (powerflex_storage_pool_logical_capacity_available_gigabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\",StoragePool=~\"$StoragePool\",StorageSystemName=~\"$StorageSystemName\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Free Capacity"
    },
    {
     "alias": "Provisioned",
     "expr": "avg by (StoragePool) (powerflex_storage_pool_logical_provisioned_gigabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\",StoragePool=~\"$StoragePool\",StorageSystemName=~\"$StorageSystemName\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Provisioned"
    }
   ]
  },
  {
   "title": "Capacity Summary",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 21 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "Used Capacity",
     "expr": "avg by (StoragePool) (powerflex_storage_pool_logical_capacity_in_use_gigabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\",StoragePool=~\"$StoragePool\",StorageSystemName=~\"$StorageSystemName\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Used Capacity",
     "select": [
      [
       { "params": [ "used_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Free Capacity",
     "expr": "avg by (StoragePool) (powerflex_storage_pool_logical_capacity_available_gigabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\",StoragePool=~\"$StoragePool\",StorageSystemName=~\"$StorageSystemName\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Free Capacity",
     "select": [
      [
       { "params": [ "capacity_latest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}