{
 "title": "PowerStore Storage Class Capacity_3",
 "description": "PowerStore Storage Class Capacity",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "StorageClass",
    "label": "Storage Class",
    "query": "label_values(powerstore_storage_class_logical_provisioned_megabytes, StorageClass)"
   },
   {
    "name": "Driver",
    "query": "label_values(powerstore_array_logical_provisioned_megabytes, Driver)"
   },
   {
    "name": "ArrayID",
    "label": "Array ID",
    "query": "label_values(powerstore_array_logical_provisioned_megabytes, ArrayID)"
   }
  ]
 },
 "panels": [
  { "title": "Storage Class Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage Capacities",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "powerstore_storage_class_logical_provisioned_megabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\"}"
    },
    {
     "expr": "powerstore_storage_class_logical_used_megabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\"}"
    }
   ]
  },
  {
   "title": "Storage Class Usage",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_source",
     "expr": "avg by (ArrayID) (powerstore_array_logical_used_megabytes{Driver=~\"$Driver\",ArrayID=~\"$ArrayID\"}*100 / powerstore_array_logical_provisioned_megabytes{Driver=~\"$Driver\",ArrayID=~\"$ArrayID\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{StoragePool}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Array Capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Capacity",
     "expr": "avg by (ArrayID) (powerstore_array_logical_provisioned_megabytes{Driver=~\"$Driver\",ArrayID=~\"$ArrayID\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Provisioned"
    },
    {
     "alias": "Free Capacity",
     "expr": "avg by (ArrayID) (powerstore_array_logical_used_megabytes{Driver=~\"$Driver\",ArrayID=~\"$ArrayID\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Capacity Summary",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Used Capacity",
     "expr": "avg by (ArrayID) (powerstore_array_logical_used_megabytes{Driver=~\"$Driver\",ArrayID=~\"$ArrayID\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Used Capacity",
     "select": [
      [
       { "params": [ "used_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Free Capacity",
     "expr": "avg by (ArrayID) (powerstore_array_logical_provisioned_megabytes{Driver=~\"$Driver\",ArrayID=~\"$ArrayID\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Provisioned Capacity",
     "select": [
      [
       { "params": [ "capacity_latest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Array Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Array Capacities",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "powerstore_array_logical_provisioned_megabytes{Driver=~\"$Driver\",ArrayID=~\"$ArrayID\"}"
      },
      {
       "expr": "powerstore_array_logical_used_megabytes{Driver=~\"$Driver\",ArrayID=~\"$ArrayID\"}"
      }
     ]
    },
    {
     "title": "Array Usage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_source",
       "expr": "avg by (ArrayID) (powerstore_array_logical_used_megabytes{Driver=~\"$Driver\",ArrayID=~\"$ArrayID\"}*100 / powerstore_array_logical_provisioned_megabytes{Driver=~\"$Driver\",ArrayID=~\"$ArrayID\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{StoragePool}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$StorageClass",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "StorageClass",
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Class Capacity",
     "type": "stat",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (StorageClass) (powerstore_storage_class_logical_used_megabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "avg by (StorageClass) (powerstore_storage_class_logical_provisioned_megabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\"})",
       "legendFormat": "Provisioned "
      }
     ]
    },
    {
     "title": "Storage Class Summary",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (StorageClass) (powerstore_storage_class_logical_used_megabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\"})",
       "legendFormat": "Used Capacity"
      },
      {
       "expr": "avg by (StorageClass) (powerstore_storage_class_logical_provisioned_megabytes{Driver=~\"$Driver\",StorageClass=~\"$StorageClass\"})",
       "legendFormat": "Provisioned"
      }
     ]
    }
   ]
  },
  { "title": "$ArrayID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }, "repeat": "ArrayID" }
 ]
}