{
 "title": "PowerStore Volume IO Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ShowMean", "label": "Hide Details", "query": "Yes, No" },
   {
    "name": "ArrayID",
    "label": "Array ID",
    "query": "label_values(powerstore_volume_read_bw_megabytes_per_second,ArrayID)"
   },
   {
    "name": "VolumeID",
    "label": "Volume ID",
    "query": "label_values(powerstore_volume_read_bw_megabytes_per_second,VolumeID)"
   },
   {
    "name": "PVName",
    "label": "PV Name",
    "query": "label_values(powerstore_volume_read_bw_megabytes_per_second,PersistentVolumeName)"
   },
   {
    "name": "PersistentVolumeClaimName",
    "label": "PVC Name",
    "query": "label_values(powerstore_volume_read_bw_megabytes_per_second,PersistentVolumeClaimName)"
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": "label_values(powerstore_volume_read_bw_megabytes_per_second,Namespace)"
   },
   { "name": "TopX", "label": "Ranking", "query": "2,5,10,15,20,100,1000" },
   {
    "name": "TimeFrame",
    "label": "Average over Time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume Mirror BW",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerstore_volume_mirror_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powerstore_volume_mirror_bw_megabytes_per_second{PlotWithMean=~ \"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{PersistentVolumeName}}"
    },
    {
     "expr": "sum(powerstore_volume_mirror_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\", PersistentVolumeName=~\"$PVName\"}) / count(powerstore_volume_mirror_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\", PersistentVolumeName=~\"$PVName\"})",
     "legendFormat": "Average mirrorBW"
    }
   ]
  },
  {
   "title": "Volume Write IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerstore_volume_write_iops_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powerstore_volume_write_iops_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{PersistentVolumeName}}"
    },
    {
     "expr": "sum(powerstore_volume_write_iops_per_second{PlotWithMean=~\"($ShowMean)|No\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"}) / count(powerstore_volume_write_iops_per_second{PlotWithMean=~\"($ShowMean)|No\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"})",
     "legendFormat": "Average WriteIOP"
    }
   ]
  },
  {
   "title": "Volume Read Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerstore_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powerstore_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{PersistentVolumeName}}"
    },
    {
     "expr": "sum(powerstore_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"}) / count(powerstore_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"})",
     "legendFormat": "Average ReadLatency"
    }
   ]
  },
  {
   "title": "Volume Write Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerstore_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powerstore_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{PersistentVolumeName}}"
    },
    {
     "expr": "sum(powerstore_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"}) / count(powerstore_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"})",
     "legendFormat": "Average WriteLatency"
    }
   ]
  },
  {
   "title": "Volume Read Bandwidth (MB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerstore_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powerstore_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{PersistentVolumeName}}"
    },
    {
     "expr": "sum(powerstore_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"}) / count(powerstore_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"})",
     "legendFormat": "Average ReadBW"
    }
   ]
  },
  {
   "title": "Volume Write Bandwidth (MB/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "powerstore_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powerstore_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PersistentVolumeClaimName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{PersistentVolumeName}}"
    },
    {
     "expr": "sum(powerstore_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"}) / count(powerstore_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"})",
     "legendFormat": "Average WriteBW"
    }
   ]
  }
 ]
}