{
 "title": "Powerstore Volume Performance metrics for Kubevirt Workloads",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "ArrayID",
    "label": "Array ID",
    "query": {
     "query": "label_values(powerstore_volume_read_bw_megabytes_per_second,ArrayID)"
    }
   },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kubevirt_vmi_info,node)"
    }
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kubevirt_vmi_info,namespace)"
    }
   },
   {
    "name": "VM",
    "label": "VM",
    "query": {
     "query": "query_result(kubevirt_vmi_info{namespace=\"$Namespace\"})"
    }
   },
   {
    "name": "VMPod",
    "label": "VMPod",
    "query": {
     "query": "query_result(kubevirt_vmi_info{namespace=\"$Namespace\", name=\"$VM\"})"
    }
   },
   {
    "name": "PVCName",
    "label": "PVCName",
    "query": {
     "query": "query_result((  powerstore_volume_read_bw_megabytes_per_second{Namespace=\"$Namespace\"}    * on(PersistentVolumeClaimName) group_left(pod)  label_replace(    kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$Namespace\", pod=\"$VMPod\"},    \"PersistentVolumeClaimName\", \"$1\", \"persistentvolumeclaim\", \"(.*)\"  ))* on(pod) group_left(name) label_replace(  kubevirt_vmi_info{namespace=\"$Namespace\", vmi_pod=\"$VMPod\"}, \"pod\", \"$1\", \"vmi_pod\", \"(.*)\"))"
    }
   },
   {
    "name": "PVName",
    "label": "PV Name",
    "query": {
     "query": "query_result((  powerstore_volume_read_bw_megabytes_per_second{Namespace=\"$Namespace\"}    * on(PersistentVolumeClaimName) group_left(pod)  label_replace(    kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$Namespace\", pod=\"$VMPod\"},    \"PersistentVolumeClaimName\", \"$1\", \"persistentvolumeclaim\", \"(.*)\"  ))* on(pod) group_left()label_replace(  kubevirt_vmi_info{namespace=\"$Namespace\", phase=\"running\"}, \"pod\", \"$1\", \"vmi_pod\", \"(.*)\"))"
    }
   },
   {
    "name": "VolumeID",
    "label": "Volume ID",
    "query": {
     "query": "query_result((  powerstore_volume_read_bw_megabytes_per_second{Namespace=\"$Namespace\"}    * on(PersistentVolumeClaimName) group_left(pod)  label_replace(    kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$Namespace\", pod=\"$VMPod\"},    \"PersistentVolumeClaimName\", \"$1\", \"persistentvolumeclaim\", \"(.*)\"  ))* on(pod) group_left()label_replace(  kubevirt_vmi_info{namespace=\"$Namespace\", phase=\"running\"}, \"pod\", \"$1\", \"vmi_pod\", \"(.*)\"))"
    }
   },
   { "name": "ShowMean", "label": "Hide Details", "query": "Yes, No" },
   { "name": "TopX", "label": "Ranking", "query": "2,5,10,15,20,100,1000" },
   {
    "name": "TimeFrame",
    "label": "Average over Time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Virtualization Topology Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Kubevirt Workloads Topology",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "powerstore_volume_read_bw_megabytes_per_second{Namespace=\"$Namespace\"} * on(PersistentVolumeClaimName) group_left(pod) label_replace(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$Namespace\", pod=~\"virt-launcher.*\"}, \"PersistentVolumeClaimName\", \"$1\",  \"persistentvolumeclaim\", \"(.*)\"  ) *on(pod) group_left(vm_name) label_replace(kube_pod_info{created_by_kind=\"VirtualMachineInstance\"}, \"vm_name\", \"$1\", \"created_by_name\", \"(.*)\") * on(vm_name) group_left(phase) label_replace(kubevirt_vmi_info{namespace=\"$Namespace\"}, \"vm_name\", \"$1\", \"name\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$PVName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "PVName" },
  {
   "title": "Volume Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "powerstore_volume_read_iops_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powerstore_volume_read_iops_per_second{PlotWithMean=~ \"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{PersistentVolumeName}}"
    },
    {
     "expr": "sum(powerstore_volume_read_iops_per_second{PlotWithMean=~\"($ShowMean)|No\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\", PersistentVolumeName=~\"$PVName\"}) / count(powerstore_volume_read_iops_per_second{PlotWithMean=~\"($ShowMean)|No\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\", PersistentVolumeName=~\"$PVName\"})",
     "legendFormat": "Average ReadIOPS"
    }
   ]
  },
  {
   "title": "Volume Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "powerstore_volume_write_iops_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powerstore_volume_write_iops_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{PersistentVolumeName}}"
    },
    {
     "expr": "sum(powerstore_volume_write_iops_per_second{PlotWithMean=~\"($ShowMean)|No\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"}) / count(powerstore_volume_write_iops_per_second{PlotWithMean=~\"($ShowMean)|No\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"})",
     "legendFormat": "Average WriteIOP"
    }
   ]
  },
  {
   "title": "Volume Read Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "powerstore_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powerstore_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{PersistentVolumeName}}"
    },
    {
     "expr": "sum(powerstore_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"}) / count(powerstore_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"})",
     "legendFormat": "Average ReadLatency"
    }
   ]
  },
  {
   "title": "Volume Write Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "powerstore_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powerstore_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{PersistentVolumeName}}"
    },
    {
     "expr": "sum(powerstore_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"}) / count(powerstore_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"})",
     "legendFormat": "Average WriteLatency"
    }
   ]
  },
  {
   "title": "Volume Read Bandwidth (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "powerstore_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powerstore_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{PersistentVolumeName}}"
    },
    {
     "expr": "sum(powerstore_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"}) / count(powerstore_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"})",
     "legendFormat": "Average ReadBW"
    }
   ]
  },
  {
   "title": "Volume Write Bandwidth (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "powerstore_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powerstore_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{PersistentVolumeName}}"
    },
    {
     "expr": "sum(powerstore_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"}) / count(powerstore_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\",VolumeID=~\"$VolumeID\", ArrayID=~\"$ArrayID\",PersistentVolumeName=~\"$PVName\"})",
     "legendFormat": "Average WriteBW"
    }
   ]
  }
 ]
}