{
 "title": "PowerMax Performance Metrics for Kubevirt Loads",
 "templating": {
  "list": [
   { "name": "ShowMean", "label": "Hide Details", "query": "Yes, No" },
   { "name": "TopX", "label": "Ranking", "query": "2,5,10,15,20,100" },
   {
    "name": "TimeFrame",
    "label": "Average over Time",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Cluster", "label": "Cluster", "query": "prometheus" },
   {
    "name": "ArrayID",
    "label": "Symmetrix ID",
    "query": {
     "query": "label_values(powermax_storage_group_average_io_size_megabytes_per_second,ArrayID)"
    }
   },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kubevirt_vmi_info,node)"
    }
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kubevirt_vmi_info,namespace)"
    }
   },
   {
    "name": "VM",
    "label": "VM",
    "query": {
     "query": "query_result(kubevirt_vmi_info{namespace=\"$Namespace\"})"
    }
   },
   {
    "name": "VMPod",
    "label": "VMPod",
    "query": {
     "query": "query_result(kubevirt_vmi_info{namespace=\"$Namespace\", name=\"$VM\"})"
    }
   },
   {
    "name": "PVCName",
    "label": "PVCName",
    "query": {
     "query": "query_result((  powermax_volume_read_bw_megabytes_per_second{Namespace=\"$Namespace\"}    * on(PersistentVolumeClaimName) group_left(pod)  label_replace(    kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$Namespace\", pod=\"$VMPod\"},    \"PersistentVolumeClaimName\", \"$1\", \"persistentvolumeclaim\", \"(.*)\"  ))* on(pod) group_left(name) label_replace(  kubevirt_vmi_info{namespace=\"$Namespace\", vmi_pod=\"$VMPod\"}, \"pod\", \"$1\", \"vmi_pod\", \"(.*)\"))"
    }
   },
   {
    "name": "PVName",
    "label": "PV Name",
    "query": {
     "query": "query_result((  powermax_volume_read_bw_megabytes_per_second{Namespace=\"$Namespace\"}    * on(PersistentVolumeClaimName) group_left(pod)  label_replace(    kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$Namespace\", pod=\"$VMPod\"},    \"PersistentVolumeClaimName\", \"$1\", \"persistentvolumeclaim\", \"(.*)\"  ))* on(pod) group_left()label_replace(  kubevirt_vmi_info{namespace=\"$Namespace\"}, \"pod\", \"$1\", \"vmi_pod\", \"(.*)\"))"
    }
   },
   {
    "name": "VolumeID",
    "label": "Volume ID",
    "query": {
     "query": "query_result((  powermax_volume_read_bw_megabytes_per_second{Namespace=\"$Namespace\"}    * on(PersistentVolumeClaimName) group_left(pod)  label_replace(    kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$Namespace\", pod=\"$VMPod\"},    \"PersistentVolumeClaimName\", \"$1\", \"persistentvolumeclaim\", \"(.*)\"  ))* on(pod) group_left()label_replace(  kubevirt_vmi_info{namespace=\"$Namespace\"}, \"pod\", \"$1\", \"vmi_pod\", \"(.*)\"))"
    }
   }
  ]
 },
 "panels": [
  { "title": "$VolumeID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "VolumeID" },
  {
   "title": "Volume Capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (VolumeID) (powermax_volume_used_capacity_gigabytes{ArrayID=~\"$ArrayID\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", VolumeID=~\"$VolumeID\", Namespace=~\"$Namespace\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (VolumeID) (powermax_volume_total_capacity_gigabytes{ArrayID=~\"$ArrayID\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", VolumeID=~\"$VolumeID\", Namespace=~\"$Namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Volume Summary",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "powermax_volume_total_capacity_gigabytes{ArrayID=~\"$ArrayID\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", VolumeID=~\"$VolumeID\", Namespace=~\"$Namespace\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "powermax_volume_used_capacity_gigabytes{ArrayID=~\"$ArrayID\", PersistentVolumeClaimName=~\"$PVCName\", PersistentVolumeName=~\"$PVName\", VolumeID=~\"$VolumeID\", Namespace=~\"$Namespace\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Storage Group Average IO Size (MB/S)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "powermax_storage_group_average_io_size_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"} and topk($TopX, avg_over_time(powermax_storage_group_average_io_size_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"}[$TimeFrame]))",
     "legendFormat": "{{ArrayID}}"
    },
    {
     "expr": "sum(powermax_storage_group_average_io_size_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", ArrayID=~\"$ArrayID\"}) / count(powermax_storage_group_average_io_size_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\",ArrayID=~\"$ArrayID\"})",
     "legendFormat": "Average IO Size"
    }
   ]
  },
  {
   "title": "Storage Group Read Bandwidth (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "powermax_storage_group_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"} and topk($TopX, avg_over_time(powermax_storage_group_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"}[$TimeFrame]))",
     "legendFormat": "{{ArrayID}}"
    },
    {
     "expr": "sum(powermax_storage_group_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", ArrayID=~\"$ArrayID\"}) / count(powermax_storage_group_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\",ArrayID=~\"$ArrayID\"})",
     "legendFormat": "Average Read Bandwidth"
    }
   ]
  },
  {
   "title": "Storage Group Write Bandwidth (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "powermax_storage_group_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"} and topk($TopX, avg_over_time(powermax_storage_group_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"}[$TimeFrame]))",
     "legendFormat": "{{ArrayID}}"
    },
    {
     "expr": "sum(powermax_storage_group_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\", ArrayID=~\"$ArrayID\"}) / count(powermax_storage_group_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)|No\",ArrayID=~\"$ArrayID\"})",
     "legendFormat": "Average Write Bandwidth"
    }
   ]
  },
  {
   "title": "Storage Group Read Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "powermax_storage_group_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"} and topk($TopX, avg_over_time(powermax_storage_group_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"}[$TimeFrame]))",
     "legendFormat": "{{ArrayID}}"
    },
    {
     "expr": "sum(powermax_storage_group_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\", ArrayID=~\"$ArrayID\"}) / count(powermax_storage_group_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\",ArrayID=~\"$ArrayID\"})",
     "legendFormat": "Average Read Latency"
    }
   ]
  },
  {
   "title": "Storage Group Write Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "powermax_storage_group_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"} and topk($TopX, avg_over_time(powermax_storage_group_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"}[$TimeFrame]))",
     "legendFormat": "{{ArrayID}}"
    },
    {
     "expr": "sum(powermax_storage_group_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\", ArrayID=~\"$ArrayID\"}) / count(powermax_storage_group_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)|No\",ArrayID=~\"$ArrayID\"})",
     "legendFormat": "Average Write Latency"
    }
   ]
  },
  {
   "title": "Storage Group Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "powermax_storage_group_read_io_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"} and topk($TopX, avg_over_time(powermax_storage_group_read_io_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"}[$TimeFrame]))",
     "legendFormat": "{{ArrayID}}"
    },
    {
     "expr": "sum(powermax_storage_group_read_io_per_second{PlotWithMean=~\"($ShowMean)|No\", ArrayID=~\"$ArrayID\"}) / count(powermax_storage_group_read_io_per_second{PlotWithMean=~\"($ShowMean)|No\",ArrayID=~\"$ArrayID\"})",
     "legendFormat": "Average Read IOPS"
    }
   ]
  },
  {
   "title": "Storage Group Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "powermax_storage_group_write_io_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"} and topk($TopX, avg_over_time(powermax_storage_group_write_io_per_second{PlotWithMean=~\"($ShowMean)\", ArrayID=~\"$ArrayID\"}[$TimeFrame]))",
     "legendFormat": "{{ArrayID}}"
    },
    {
     "expr": "sum(powermax_storage_group_write_io_per_second{PlotWithMean=~\"($ShowMean)|No\", ArrayID=~\"$ArrayID\"}) / count(powermax_storage_group_write_io_per_second{PlotWithMean=~\"($ShowMean)|No\",ArrayID=~\"$ArrayID\"})",
     "legendFormat": "Average Write IOPS"
    }
   ]
  },
  {
   "title": "Volume Read Bandwidth (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "powermax_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powermax_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{VolumeID}}"
    },
    {
     "expr": "sum(powermax_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}) / count(powermax_volume_read_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"})",
     "legendFormat": "Average Read Bandwidth"
    }
   ]
  },
  {
   "title": "Volume Write Bandwidth (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "powermax_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powermax_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{VolumeID}}"
    },
    {
     "expr": "sum(powermax_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}) / count(powermax_volume_write_bw_megabytes_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"})",
     "legendFormat": "Average Write Bandwidth"
    }
   ]
  },
  {
   "title": "Volume Read Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "powermax_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powermax_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{VolumeID}}"
    },
    {
     "expr": "sum(powermax_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}) / count(powermax_volume_read_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"})",
     "legendFormat": "Average Read Latency"
    }
   ]
  },
  {
   "title": "Volume Write Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "powermax_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powermax_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{VolumeID}}"
    },
    {
     "expr": "sum(powermax_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}) / count(powermax_volume_write_latency_milliseconds{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"})",
     "legendFormat": "Average Write Latency"
    }
   ]
  },
  {
   "title": "Volume Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "powermax_volume_read_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powermax_volume_read_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{VolumeID}}"
    },
    {
     "expr": "sum(powermax_volume_read_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}) / count(powermax_volume_read_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"})",
     "legendFormat": "Average Read IOPS"
    }
   ]
  },
  {
   "title": "Volume Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "powermax_volume_write_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"} and topk($TopX, avg_over_time(powermax_volume_write_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}[$TimeFrame]))",
     "legendFormat": "{{VolumeID}}"
    },
    {
     "expr": "sum(powermax_volume_write_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"}) / count(powermax_volume_write_io_per_second{PlotWithMean=~\"($ShowMean)\", VolumeID=~\"$VolumeID\", PersistentVolumeName=~\"$PVName\", PersistentVolumeClaimName=~\"$PVCName\",Namespace=~\"$Namespace\"})",
     "legendFormat": "Average Write IOPS"
    }
   ]
  }
 ]
}