name: Release Karavi Observability
# Invocable as a reusable workflow
# Can be manually triggered
on:  # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:
    inputs:
      option:
        description: 'Select version to release'
        required: true
        type: choice
        default: 'minor'
        options:
          - major
          - minor
          - patch
jobs:
  csm-release:
    uses: dell/common-github-actions/.github/workflows/release-creator.yaml@main
    name: Tag and Release Creator
    with:
      version: ${{ github.event.inputs.option }}
    secrets: inherit
